spring:
  application:
    name: payment-service

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    function:
      definition: processPaymentConsumer;paymentCompleted;paymentFailed
    stream:
      bindings:
        # INPUT - Comando que recibimos
        processPaymentConsumer-in-0:
          destination: process-payment-command
          group: payment-service-group

        # OUTPUTS - Eventos que enviamos
        paymentCompleted-out-0:
          destination: payment-events

        paymentFailed-out-0:
          destination: payment-events

server:
  port: 8083