spring:
  application:
    name: payment-service

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin}

  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  cloud:
    function:
      definition: processPaymentConsumer;paymentCompleted;paymentFailed
    stream:
      bindings:
        processPaymentConsumer-in-0:
          destination: process-payment-command
          group: payment-service-group
        paymentCompleted-out-0:
          destination: payment-events
        paymentFailed-out-0:
          destination: payment-events

server:
  port: 8083