spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:inventorydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    stream:
      bindings:
        reserveInventoryCommand-in-0:
          destination: reserve-inventory-command
          group: inventory-service
        releaseInventoryCommand-in-0:
          destination: release-inventory-command
          group: inventory-service
        inventoryReservedEvent-out-0:
          destination: inventory-reserved-event
        inventoryRejectedEvent-out-0:
          destination: inventory-rejected-event
      rabbit:
        bindings:
          reserveInventoryCommand-in-0:
            consumer:
              autoBindDlq: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

server:
  port: 8082
