spring:
  application:
    name: inventory-service

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  datasource:
    url: jdbc:h2:mem:inventorydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    function:
      definition: reserveInventoryCommand;releaseInventoryCommand;inventoryReservedEvent;inventoryRejectedEvent
    stream:
      bindings:
        # INPUTS - Comandos que recibimos
        reserveInventoryCommand-in-0:
          destination: reserve-inventory-command
          group: inventory-service

        releaseInventoryCommand-in-0:
          destination: release-inventory-command
          group: inventory-service

        # OUTPUTS - Eventos que enviamos
        inventoryReservedEvent-out-0:
          destination: inventory-events

        inventoryRejectedEvent-out-0:
          destination: inventory-events

server:
  port: 8082